### ISSUE TITLE
TODO: consider a cache of encrypted_key => CEKs to reduce unwrapping

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/minimal-cipher#37] opened 2021-11-30 13:45 UTC
- [ ] TODO: consider a cache of encrypted_key => CEKs to reduce unwrapping
      Commit: (4efdf85) Add TODO.
      Fi[DecryptTransformer.js:106](https://github.com/digitalbazaar/minimal-cipher/blob/master/DecryptTransformer.js#L106)
      Dave Longley commented 2 years ago

**Comment by dlongley** [comment] 2022-07-31 15:29
Duplicate of #30.

**Closed as completed by dlongley** 2022-07-31 15:29 UTC
