### ISSUE TITLE
FIXME for FIPs Compliance 

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/minimal-cipher#19] opened 2020-07-06 20:50 UTC
In the [fips.js](https://github.com/digitalbazaar/minimal-cipher/blob/master/algorithms/fips.js#L7) file there is a FIXME stating it is not yet FIPs compliant.

**Comment by mandyvenables** [comment] 2020-07-06 20:51
@dlongley what is the priority on this issue?

**Comment by dlongley** [comment] 2022-07-31 15:31
Duplicate of #24.

**Closed as completed by dlongley** 2022-07-31 15:31 UTC
